name = 'mysite'
post_import = ''
include = []

[[env]]
key = "PIDFILE"
value = "/tmp/server.pid"

[[env]]
key = "BRIDGETOWN_ENV"
value = "production"

[services.web]
port = 4000

[build]
onbuild = [
  "apt-get update",
  "apt-get install -y npm",
  "npm install",
  "bin/bridgetown deploy"
]
